// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH4nDw40VUnaUpflJU7Ut4SknbXp5DmTI',
    appId: '1:42143938526:web:placeholder',
    messagingSenderId: '42143938526',
    projectId: 'team-teleprompter',
    authDomain: 'team-teleprompter.firebaseapp.com',
    storageBucket: 'team-teleprompter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuwqGr8zDwCBsMXJqO4_GIUOZcThm7kMs',
    appId: '1:42143938526:android:78fb3dfb485e6f9f6ccf4f',
    messagingSenderId: '42143938526',
    projectId: 'team-teleprompter',
    storageBucket: 'team-teleprompter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4nDw40VUnaUpflJU7Ut4SknbXp5DmTI',
    appId: '1:42143938526:ios:d6fc5883231e56846ccf4f',
    messagingSenderId: '42143938526',
    projectId: 'team-teleprompter',
    storageBucket: 'team-teleprompter.firebasestorage.app',
    iosBundleId: 'com.wordnerd.teamteleprompter',
  );
}
